title = "Taein's dev"
description = "functional programming, static types, programming language research, logical inference"
base_url = "https://initprism.com"
default_language = "en"

compile_sass = true
build_search_index = true
highlight_theme = "charcoal"
generate_feed = true

taxonomies = [{ name = "tags" }]

[markdown]
highlight_code = true
extra_syntaxes = ["syntaxes"]

[extra.author]
name = "TaeinKim"